apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`server1.cluster`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
