crds:
  create: false

grafana:
  service:
    type: ClusterIP
    port: 80
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi

prometheus:
  prometheusSpec:
    remoteWriteDashboards: false
    serverSideApply: true
    retention: 12h
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        memory: 3Gi
        cpu: 500m
      limits:
        memory: 6Gi
        cpu: 2
