apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.local.cluster`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80
